# Generated by Django 4.2.6 on 2023-11-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitter_app", "0003_bite"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
